export const SigninType = {
    SIGNIN_SUCCESS: "SIGNIN_SUCCESS",
    SIGNIN_FAIL: "SIGNIN_FAIL",
    SIGNIN_REQUEST: "SIGNIN_REQUEST",
    GOOGLE_SIGNIN: "GOOGLE_SIGNIN",
    FORGET_PASSWORD: "FORGET_PASSWORD",
    RESET_PASSWORD: "RESET_PASSWORD",
    SIGNOUT: "SIGNOUT",
    AUTH_ERROR: "AUTH_ERROR",
  };
  